smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1  BOB-OMB GUDALOSTEA"),	("BOB-OMB ERREGE HANDIA GAURREAN"),	("LASTERKETA KOOPA AZKARKIN"),	("TIRO EGIN ZERUKO UHARTEARI"),	("BILATU 8 TXANPON GORRIAK"),	("MARIO HEGALDARIA ZERURANTZ"),	("KATE-TXOMP-AREN KAIOLAREN ATZEAN"))

smlua_text_utils_course_acts_replace(COURSE_WF, (" 2 WHOMP GOTORLEKUA"),	("ZAPALDU WHOMP HANDIA"),	("GOTORLEKUAREN GAILURRERA"),	("EGAN EGIN PLATAFORMA HANDIRANTZ"),	("8 TXANPON GORRI UHARTE MUGIKORREAN"),	("ERORI KAIOLATUTAKO UHARTERRA"),	("EGIN TALKA HARRESIAREN AURKA"))

smlua_text_utils_course_acts_replace(COURSE_JRB, (" 3 JOLLY ROGER BADIA"),	("ONTZI ONORATUKO ALTXORRA"),	("IRTEN DAITEKE ANGILA JOLASTERA?"),	("ALTXORRA ITSASOKO LEIZEAN"),	("TXANPON GORRIAK URETAN DAGOEN ONTZIAN"),	("EGIN TALKA HARRIZKO ZUTABEAREN KONTRA"),	("KORRONTEAN ZAHAR"))

smlua_text_utils_course_acts_replace(COURSE_CCM, (" 4 MENDI IZOZTUA"),	("IRRISTATZEN HELMUGARANTZ"),	("PINGUINOTXO GALDUA..."),	("LASTERKETA PINGUINO HANDIAREN AURKA"),	("IRRISTATZEN 8 TXANPON GORRIEN BILA"),	("ELURREZKO PANPINAK BURUA GALDU DU"),	("HORMA-JAUZI ESKOLA"))

smlua_text_utils_course_acts_replace(COURSE_BBH, (" 5 ETXE SORGINDUA"),	("BOO-EN GARAIA"),	("IGO BOO ZALDITXO-MUGIKORRERA"),	("LIBURUTEGIKO SEKRETUA"),	("BILATU 8 TXANPON GORRIAK"),	("BOO HANDIAREN BALKOIA"),  ("BEGI BAT GELA SEKRETUAN"))

smlua_text_utils_course_acts_replace(COURSE_HMC, (" 6 LABIRINTOKO LEIZEA"),	("URETAKO PIZTIA LEIZEAN"),	("IGO 8 TXANPON GORRIENGATIK"),	("MARIO BURDIN-BURUA, MUGI!"),	("NABIGATZEN LAUSO POZOITSUAN"),	("SWOOP-AREN IHESALDIA!"),	("KONTUZ! HARRI BIRAKARIAK"))

smlua_text_utils_course_acts_replace(COURSE_LLL, (" 7 LAVA LURRALDEA"),	("SUKALDARITZAN BULLY HANDIAREKIN"),	("HIRU BULLY MATOI"),	("8 TXANPON GORRI BURUHAUSTEAN"),	("ENBOR BIRAKARI BEROA"),	("OIN BEROAK SUMENDIAN"),	("LIFT BIDAIA SUMENDI BARRUAN"))

smlua_text_utils_course_acts_replace(COURSE_SSL, (" 8 HARE MUGIKORRAK"),	("TXORI HANDIAREN ORPOETAN"),	("DISTIRA PIRAMIDEAREN GAILURREAN"),	 antzinako PIRAMIDE BARRUAN"),	("ZUTIK 4 ZUTABEEN GAINEAN"),	("EGAN 8 TXANPON GORRIENGATIK"),	("PIRAMIDEKO BURUHAUSTEA"))

smlua_text_utils_course_acts_replace(COURSE_DDD, (" 9 KAIA ZORITXARREKOA"),	("BOWSER-EN ITSASPEKOAN"),	("KUTXAK KORRONTEAREN AURKA"),	("TXANPON GORRIAK ZUTABEETAN"),	("KORRONTE BARRUAN"),	("MANTA ARRAINAREN SARIA"),	("TXAPELA BILDUMA..."))

smlua_text_utils_course_acts_replace(COURSE_SL, (" 10 LURRALDE IZOZTUA"),	("ELURREZKO PANPINA BURUHANDIA"),	("IZOZTALDU BULLY-A"),	("HOTZ SAKONEAN"),	("IHESI IZOZTUTAKO URTEGITIK"),	("DOSTALLA TXANPON GORRIENGATIK"),	("IGLU BARRUAN"))

smlua_text_utils_course_acts_replace(COURSE_WDW, (" 11 BELAUKI HIRIA"),	("GEZI ELEKTRIKO HARRIGARRIAK!"),	("HIRIAREN GAILURRA"),	("SEKRETUAK ALTUERAN"),	("ELEVADORE AZKARRA: AZKARTU!!"),	("ZOAZ HIRIRA TXANPON GORRIEN BILA"),	("LASTERKETA AZKARRA HIRIAN!"))

smlua_text_utils_course_acts_replace(COURSE_TTM, ("12 MENDI MALDANTSUA"),	("ESKALADA MENDIAN"),	("KAIOLATUTAKO TZINPANTZEAREN MISTERIOA"),	("ONDDOKO IKARAGARRIAK, TXANPON GORRIAK"),	("MENDIKO TOBOGAN MISTERIOTSUA"),	("UR-JAUZIAREN ATZEAN"),	("TIROA ONDDO BAKARTIARI"))

smlua_text_utils_course_acts_replace(COURSE_THI, ("13 UHARTE HANDI-TXIKIA"),	("KENDU PIRAINIA LANDAREA"),	("UHARTE HANDIAREN GAILURRA"),	("BERREVANKA KOOPA AZKARKIN"),	("5 SEKRETUTXO OSO TXIKIAK"),	("WIGGLER-AREN TXANPON GORRIAK"),	("EGIN WIGGLER BIHURRICATU DADIN"))

smlua_text_utils_course_acts_replace(COURSE_TTC, ("14 TIK-TAK ERLOJU"),	("ERROLDATU KAIOLARA ARTE"),	("PENDULUAK ETA ZIKINA"),	("ORRATO BAT BEHAR DUZU?"),	("THWOMP BATEN GAINEAN"),	("PLATAFORMEN RITMORA"),	("TXANPON GORRIAK DENBORAZ KANPO"))

smlua_text_utils_course_acts_replace(COURSE_RR, (" 15 ORTZADARREKO BIDAIA"),	("IBILALDIA ORTZADARREAN"),	("ETXEA ZERUAN"),	("TXANPON NAHASIAK LABIRINTOAN"),	("KULUNKA HAIZE BARRUAN"),	("TRIANGELU TRUKUDUNAK!"),	("NONBAIT ORTZADARRETIK GORANTZ"))

smlua_text_utils_secret_star_replace(COURSE_BITDW,    "   BOWSER ILUNPEAN")
smlua_text_utils_secret_star_replace(COURSE_BITFS,    "   BOWSER LAVA ITSASOAN")
smlua_text_utils_secret_star_replace(COURSE_BITS,     "   BOWSER ZERUAN")
smlua_text_utils_secret_star_replace(COURSE_PSS,      "   PRINTZESAREN TOBOGAN SEKRETUA")
smlua_text_utils_secret_star_replace(COURSE_COTMC,    "   BURDINEZKO TXAPELAREN LEIZEA")
smlua_text_utils_secret_star_replace(COURSE_TOTWC,    "   TXAPEL HEGALDARIAREN DORREA")
smlua_text_utils_secret_star_replace(COURSE_VCUTM,    "   TXAPEL IKUSEZINAREN HOBIA")
smlua_text_utils_secret_star_replace(COURSE_WMOTR,    "   MARIO HEGALDARIA ORTZADARRAREN GAINEAN")
smlua_text_utils_secret_star_replace(COURSE_SA,       "   AKUARIO SEKRETUA")

smlua_text_utils_secret_star_replace(COURSE_CAKE_END, "")

smlua_text_utils_castle_secret_stars_replace("   IZAR SEKRETUAK")

smlua_text_utils_extra_text_replace(0, "¡GAZTELUKO IZAR SEKRETUETAKO BAT!")
smlua_text_utils_extra_text_replace(1,(""))
smlua_text_utils_extra_text_replace(2,(""))
smlua_text_utils_extra_text_replace(3,(""))
smlua_text_utils_extra_text_replace(4,(""))
smlua_text_utils_extra_text_replace(5,(""))
smlua_text_utils_extra_text_replace(6,(""))
